[package]
name = "bullethell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", features = ["dynamic"] }
bevy_ecs_tilemap = { version = "0.5" }
rand = "0.8.5"
